{% set name = "flexx" %}
{% set version = "0.8.0" %}
{% set sha256 = "ee7de225aac13ea1a03c4bc7460dde89b39b8c3ca71d1e024926ef9f02b872dd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0
  entry_points:
    - flexx = flexx.__main__:main

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - pscript
    - webruntime
    - dialite
    - tornado

test:
  imports:
    - flexx.flx

about:
  home: http://github.com/flexxui/flexx
  doc_url: http://flexx.readthedocs.io
  dev_url: http://github.com/flexxui/flexx
  summary: Python UI tookit based on web technology
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
    - ivoflipse
