travis:
  secure:
    BINSTAR_TOKEN: KrFpr/0aCBAcgVfPd2j31YnXzmWx/V0J5aqqPCmDDxU5sSNIyImh3gTLta/I+hMc3qC9dJ2D02NJTL9QkwxPsoMrQ4RvtC9/WBw37ogA1DDGltkMzuTGFfG6458JySn/2F55o7liy3vfc844th2aa9x6J6xb/TWlR3sKKKMOIp3Utz5uKgh9NKkZ9492+rdapl3ojdHo2v1CDtmJ/RbkxGWLLDgihwpSfr1+gn676ZYevPpNTt9nXvvfyAYwswy1V/KMB0iNhqTY12RucWCFK+w1caWzIM8zRVsEFW6NZwF1AwC1nNdqjuh9WJC/2TsS6zVv6pnEntQlaTHAcDvgLS6e216OUQ2rGn1/1s4paXKV8J7aHE3/Jg4lUsIFVr4CRalkjUaufShe+vRrQEFWNMIpgUOrQ0NkvHIg/bxc6fNKACBbbuTGXRSvJEVprumIIc11hJGrCAFb2WEFwxMMuE5zHJ7n6l5ADXxB6ayxQroZnlpuK6/soYyyTDMAjIxUmPTaR3YSTrWlmFGWLmHgPU/2P/GhLU+G8ggwJ3+mK0WY/leAiNOoWSw+CYulBUxEncpeGM8chHFf5uBZbiqJchk8PUeewVe1vn3Cs8js0h6Bv73MsrGPo70fKVNt4D+jDyBHEE5UJcy87Ewe9LvV6K8lXRa/9xDO40okl1x5VKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
